version: '3.2'

services:
  agent:
    image: portainer/agent
    container_name: portainer_agent
    # environment:
      # AGENT_PORT: Port Agent will run on within the container. (Defaults to 9001)
      # AGENT_HOST: Host Agent will listen on within the container. (Defaults to 0.0.0.0)
      # AGENT_SECRET: Agent Secret used by Portainer to connect to Agent from multiple sources.
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker/volumes
        target: /var/lib/docker/volumes
    ports:
      - ${AGENT_PUBLISHED_PORT}:${AGENT_PORT}/tcp
    labels:
      - "io.portainer-ce.hidden=1"

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    # environment:
      # PORTAINER_PORT: Port Portainer will run on within the container. (Defaults to 9000)
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: data
        target: /data
    ports:
      - ${PORTAINER_PUBLISHED_PORT}:${PORTAINER_PORT}
    labels:
      - "io.portainer-ce.hidden=1"
    command: --host unix:///var/run/docker.sock --tlsskipverify --hide-label io.portainer-ce.hidden=1

volumes:
  data:
    labels:
      - "io.portainer-ce.hidden=1"
