version: '3.2'

services:
  agent:
    image: portainer/agent
    container_name: portainer_agent
    # environment:
    #  AGENT_PORT: Port Agent will run on within the container. (Defaults to 9001)
    #  AGENT_HOST: Host Agent will listen on within the container. (Defaults to 0.0.0.0)
    #  AGENT_SECRET: Agent Secret used by Portainer to connect to Agent from multiple sources.
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /volume1/@docker/volumes
        target: /var/lib/docker/volumes
    # - type: bind
    #   source: /
    #   target: /host
    ports:
      - ${AGENT_PUBLISHED_PORT}:${AGENT_PORT}/tcp
    networks:
      - agent
    restart: unless-stopped
    labels:
      - "io.portainer-ce.hidden=1"
networks:
  agent:
    driver: bridge
    attachable: true
    labels:
      - "io.portainer-ce.hidden=1"
